print("Welcome to Treasure Island! Your mission is to find the treasure.")
A = input("Which way do you go? (0=Left, 1=Right)")

if A == "0":
  B = input("You see a river, what will you do? (0=Wait, 1=Swim)")
else:
  print("You fall to a spike trap and Died!!!")
  print("< Game Over >")
  quit()

if B == "0":
  C = input("You wait for a while and three doors appear out of nowhere, which door do you enter? (0=Red Door, 1=Yellow Door, 2=Blue Door)")
else:
  print("You jump into the river and try to cross it, but the current is to strong and you drowned!!!")
  print("< Game Over >")
  quit()

if C == "1":
  print("You open the Yellow Door and found a treasure chest.")
  print("You open the treasure chest.")
  print("You recieve 10.000 Gold Coins")
  print("Dun Dun Dun")
  print("< Congratulation >")
  quit()
elif C == "0":
  print("You open the Red Door and found a long hallway")
  print("You walk trough the hallway.")
  print("After an hour you foung a wooden door")
  print("You open the door and found yourself in a mansion")
  print("You tought you can found the treasure in the mansion, so you explore the mansion.")
  print("You keep searching for the treasure")
  print("You keep searching for the treasure")
  print("You keep searching for the treasure...")
  print("You keep searching...")
  print("You keep searching......")
  print("You keep searching.........")
  print("Searching...")
  print("Searching......")
  print("Searching.........")
  print("Searchi...")
  print("Sear... ching...")
  print("ser....")
  print("...")
  print("...")
  print("...")
  print("< Congratulation? >")
  quit()
else:
  print("You open the Blue Door and fall to a spike trap")
  print("But you didn't died")
  print('"What happened?" you ask')
  print("Suddenly a lightning struck you")
  print("You immedietly awaken")
  print("Turn out it's just a dream")
  print("You lay your body to the bed")
  print("And continue your sleep")
  print("...")
  print("...")
  print("...")
  print("But today is monday")
  print("Your Boss won't be happy")
  print("< Work Over >")
  quit()